### ISSUE TITLE
Request: update sample and repository webpage

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [zjupure/GlideWebpDecoder#14]
This isn't available anymore when using the instructions on the repository:

```
Transformation<Bitmap> circleCrop = new CircleCrop();
GlideApp.with(mContext)
        .load(url)
        .optionalTransform(circleCrop)
        .optionalTransform(WebpDrawable.class, new WebpDrawableTransformation(circleCrop))
        .into(imageView);
```

Instead of "GlideApp", we have just "Glide", and there is no "optionalTransform". Instead we have "apply".

It even says so on the links of the repository:

https://github.com/wasabeef/glide-transformations
https://bumptech.github.io/glide/doc/transformations.html

Attached sample POC that follows the instructions, but if you use the code in the instructions, it will fail to build.

[AnimatedWebPTest.zip](https://github.com/zjupure/GlideWebpDecoder/files/2318227/AnimatedWebPTest.zip)

**Comment by zjupure** [comment]
See [Generated API](https://bumptech.github.io/glide/doc/generatedapi.html) for detail. 

Create a AppGlideModule implementation in your application and annotate it with @GlideModule and then GlideApp will be generated.

It is a more easy way to use for Glide v4. If you still like using an old way, it is just ok and call the correposing API instead.

**Comment by AndroidDeveloperLB** [comment]
Seems I still have an issue with this. Even without any code, it shows me a lot of errors in the form of :

```
e: C:\Users\user\Desktop\AnimatedWebPTest\app\build\generated\source\kapt\debug\com\example\user\animatedwebptest\GlideOptions.java:48: error: cannot find symbol
  @CheckResult
   ^
  symbol:   class CheckResult
  location: class GlideOptions

```

Also, it is said here that I should put the Glide version to this:

`implementation "com.zlc.glide:webpdecoder:1.0.${GLIDE_VERSION}"`

When I put 4.8.0, it fails.

Attached POC sample project.
[AnimatedWebPTest.zip](https://github.com/zjupure/GlideWebpDecoder/files/2320437/AnimatedWebPTest.zip)

**Comment by zjupure** [comment]
Glide 4.7.1 do not support AndroidX. Glide 4.8.0 release just  a week ago and has breaking api changes. I have not released the library that can work with Glide 4.8.0

This library cannot compile with Glide 4.8.0 and it needs some time to adapter it. You can replace the AndroidX dependency to traditional appcompat-v7 library and it will work as normal.

gradle.properties in project root directory
```
android.useAndroidX=false
android.enableJetifier=false
```

build.gradle
```
implementation 'androidx.appcompat:appcompat:1.0.0-rc01' 
===> implementation 'com.android.support:appcompat-v7:27.1.1'
```

Hope it will help you and get demo running success!

**Comment by AndroidDeveloperLB** [comment]
Why does it need support library at all?
It's just a decoder of webP files, no ? A decoder is supposed to be pure Java (or kotlin), with minimal to none correlation with what's around it. You give it a file, and it decodes it to something useful...

I've tried to go back to old Android support library as you wrote. It builds fine, but when I try to write code as you wrote, it doesn't accept it. As soon as I write "GlideApp.with()", it doesn't even let me write "load" :

![image](https://user-images.githubusercontent.com/5357526/44618547-a1490e80-a880-11e8-9473-c07e228713d1.png)

[AnimatedWebPTest.zip](https://github.com/zjupure/GlideWebpDecoder/files/2320702/AnimatedWebPTest.zip)

**Comment by zjupure** [comment]
Glide and this library are all developed for `Android Platform` not pure Java. Glide uses android support library to back compatible to low API version such as 14. A webp/gif file is decoded into something useful. In android platform, something useful means bitmap or drawable that can be drawn to canvas.

Glide.with() not Glide.get(), please correct it in your AS editor.

**Comment by AndroidDeveloperLB** [comment]
Oops sorry for the "get" thing. I'm used to this for singletons...

But using what you've written, I'm trying for example to use it as a Drawable or GifDrawable, and it only shows the first frame of the animation. Not only that, but using `centerCrop()` instead of `optionalTransform` shows nothing, and using `optionalTransform` with `CircleCrop` doesn't work if I try to use `asGif` instead of `asDrawable` .

How could it be?

About Glide, does it not support Android-X ? Should be automatic support as I've read, because the `enableJetifier` does it quite well. Which parts of the support library does it need?

**Comment by AndroidDeveloperLB** [comment]
1. Attached, but now that you show that I need to call "start" , it works. 
However, center-cropping doesn't work, not for webp and not for gif. Somehow CircleCrop works for both.

[AnimatedWebPTest.zip](https://github.com/zjupure/GlideWebpDecoder/files/2321257/AnimatedWebPTest.zip)

2.3. I see. You got it ready for 4.8.0 ? I thought it's not ready.

**Comment by AndroidDeveloperLB** [comment]
@zjupure Why the center-cropping doesn't work?
And how can I go one bitmap after another?
